name: Playit RDP Tunnel with Windows 11

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install QEMU and Required Packages from Alternative Repository
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:jacob/virtualisation
        sudo apt update
        sudo apt install -y qemu qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager wget

    - name: Create VM Disk Image
      run: |
        qemu-img create -f qcow2 windows11.qcow2 20G

    - name: Download Windows 11 ISO
      run: |
        wget -O windows11.iso https://software-download.microsoft.com/db/Win11_English_x64.iso

    - name: Create Script to Run QEMU with Windows 11
      run: |
        cat <<EOF > run_windows11.sh
        #!/bin/bash

        # Define variables
        ISO_PATH="./windows11.iso"
        DISK_PATH="./windows11.qcow2"
        RAM_SIZE="\$(grep MemTotal /proc/meminfo | awk '{print \$2}')K"
        CPU_CORES="4"

        # Run QEMU
        qemu-system-x86_64 \\
            -m \${RAM_SIZE} \\
            -smp \${CPU_CORES} \\
            -boot d \\
            -cdrom \${ISO_PATH} \\
            -drive file=\${DISK_PATH},if=virtio \\
            -net nic -net user,hostfwd=tcp::3389-:3389 \\
            -vga std \\
            -device virtio-balloon \\
            -vnc :1
        EOF

    - name: Make Script Executable
      run: |
        chmod +x run_windows11.sh

    - name: Start the VM
      run: |
        ./run_windows11.sh &

    - name: Download and Install Playit
      run: |
        curl -L -o playit-linux https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64
        chmod +x playit-linux
        ./playit-linux --secret 3ecc7f9c1cb0cf0849d8aab4c3ad350d02cf125be4c5dee1f0e76198ff877d33 &

    - name: Keep the GitHub Action Runner Alive
      run: |
        sleep 11800  # Adjust the duration based on your needs
